name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get Buildozer Action
        uses: ArtemGovorov/buildozer-action@v1
        with:
          command: buildozer android release
          repository_root: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YuMusic-APK
          path: bin/*.apk
